services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
forward:
      - 6379:redis:6379
volumes:
  redis-data:

build:
  hello-world:
    image: okteto.dev/java-maven-hello-world:1.0.0
    context: .
deploy:
  - kubectl apply -f k8s.yml
dev:
  hello-world:
    image: okteto/maven:3
    command: bash
    sync:
      - .:/usr/src/app
    forward:
      - 5005:5005
    volumes:
      - /root/.m2

